function reportstrs = designreport_RADIAL_SLOTTED(design, simoptions, reportstrs)
% produces a slotted radial flux electrical machine design report in LaTeX
% format, and optionally prduces the pdf using pdflatex
%
% designreport_RADIAL_SLOTTED can also be used to extend a report produced
% by a higher level function by passing in the existing report strings.
%
% Syntax
%
% designreport_RADIAL_SLOTTED(design, simoptions)
% designreport_RADIAL_SLOTTED(design, simoptions, reportstrs)
% reportstrs = designreport_RADIAL_SLOTTED(...)
%
% 
% Input
%
%
% Output
%
%   reportstrs - cell array of strings containing the report
%

    if nargin < 3
        reportstrs = {};
    end
    
    % make up report on things specific to radial slotted
    % radial flux armature dimensions
    tabledata = { ...
        '$R_{yi}$', 'Inner armature yoke radius. (m)', design.Ryi;
        '$R_{yo}$', 'Outer armature yoke radius. (m)', design.Ryo;
        '$R_{ym}$', 'Mean armature yoke radius. (m)', design.Rym;
        '$R_{ci}$', 'Inner coil radius. (m)', design.Rci;
        '$R_{co}$', 'Outer coil radius. (m)', design.Rco;
        '$R_{cm}$', 'Mean coil radius. (m)', design.Rcm;
        '$R_{tsb}$', 'Tooth shoe surface radius (m)', design.Rtsb;
        '$\theta_{cg}$', 'Internal slot pitch angle at gap end. (rad)', design.thetacg;
        '$\tau_{cg}$', 'Internal slot pitch at gap end. (m)', design.thetacg.*design.Rtsb;
        '$\theta_{cy}$', 'Internal slot pitch angle at yoke end. (rad)', design.thetacy;
        ...'$\tau_{cy}$', 'Internal slot pitch at yoke end. (m)', design.thetacy.*design.Ryo;
        '$y_d$', 'Coil pitch in slots. (No. Of Slots)', design.yd;
        '$\theta_{c}$', 'Coil pitch. (rad)', design.yd*design.thetas;
        '$\tau_{c}$', 'Coil pitch at mean coil radius. (m)', design.yd*design.thetas*design.Rcm;
        '$\theta_{s}$', 'Slot centers pitch angle. (rad)', design.thetas;
        '$\theta_{sg}$', 'Slot opening angle. (rad)', design.thetasg;
        '$t_c$', 'Coil slot height in the radial direction. (m)', design.tc;
        '$t_y$', 'Coil yoke thickness in the radial direction. (m)', design.ty;
        '$t_{sb}$', 'Coil shoe thickness where shoe meets tooth. (m)', design.tsb;
        '$t_{sg}$', 'Coil shoe thickness at coil slot opening. (m)', design.tsg;
    };

    % generate the LaTex table of the outputs
    colheadings = {};
    rowheadings = {};
    colsep = ' & '; 
    rowending = ' \\';
    fms = '.3f';

    fname = tempname;
    
    fid = fopen(fname, 'w');
    
    if fid == -1
        error('Temporary file could not be opened.');
    end
    
    displaytable(tabledata, colheadings, [30,60,20], fms, rowheadings, fid, colsep, rowending);
    
    % close the file
    fclose(fid);
    
    radarmdimstablestrs = txtfile2cell(fname);
    
radslottedreportstrs = [{...
'% Beginning section of report generated by designreport_RADIAL_SLOTTED.m';
'\section{Dimensions of the design}'; 
'The dimensions of the slotted radial flux design.';
'';
'\begin{table}[htb]';
'\centerline{';
'\begin{tabular}{lll}'
'\toprule';
'Dimension & Description & Value \\';
'\midrule';
}; ...
radarmdimstablestrs;
{...
'\bottomrule';
'\end{tabular}';
'}';
'\caption{Armature dimensions.}';
'\end{table}';
'% FloatBarrier requires the placeins package';
'\FloatBarrier{}';
'';
}; ...
];
    
    % append stuff common to all maradial machines
    radslottedreportstrs = designreport_RADIAL(design, simoptions, radslottedreportstrs);

        % append the report strings
    reportstrs = [ reportstrs;
                   radslottedreportstrs ];
               
end
