function quitallslaves(filepath)
% deletes all mat files starting with slaveID_ in the given directory in
% order to request all multicore slaves using the directory, and the
% standard slave ID file name to self terminate
%
% Syntax
%
% quitallslaves(filepath)
%
% Description
%
% filepath is the directory in which the slave Id files generated by
% startmulticoreslave2 will be found.
%

    delete(fullfile(filepath, 'slaveID_*.mat'));
    
end