function [FemmProblem, outernodes, coillabellocs, slotinfo] = axialfluxstatorhalf2dfemmprob(slots, Poles, ypole, ycoil, yshoegap, xyoke, xcoil, xshoebase, xshoegap, xoffset, side, varargin)
% draw internal parts of half a slotted axial flux stator
%
% Syntax
%
% [FemmProblem, outernodes, coillabellocs] = ...
%       axialfluxstatorhalf2dfemmprob(slots, Poles, ypole, ycoil, yshoegap, ...
%       xyoke, xcoil, xshoebase, xshoegap, xoffset, side, varargin)
%
%
% Input
%

    Inputs.NWindingLayers = 1;
    Inputs.FemmProblem = newproblem_mfemm('planar');
    Inputs.ToothMaterial = 1;
    Inputs.ToothRegionMeshSize = -1;
    Inputs.ShoeGapMaterial = 1;
    Inputs.ShoeGapRegionMeshSize = -1;
    Inputs.Tol = 1e-5;
    Inputs.CoilBaseFraction = 0.05;
    Inputs.ShoeCurveControlFrac = 0.5;
    Inputs.SplitX = false;
    Inputs.DrawCoilInsulation = false;
    Inputs.CoilInsulationThickness = 0;
    
    % check an integer number of machine Poles and slots (can't have half a
    % slot or a pole in a machine
    slots = round(slots);
    Poles = round(Poles);
    
    slotsperpole = slots / Poles;
    
    % make enugh slots for two poles by default
    Inputs.NSlots = slotsperpole * 2;
    
    Inputs = parse_pv_pairs(Inputs, varargin);
    
    % copy over the FemmProblem
    FemmProblem = Inputs.FemmProblem;
    
    % remove the odl one to save memory
    Inputs = rmfield(Inputs, 'FemmProblem');
    
    [FemmProblem, outernodes, coillabellocs, slotinfo] = ...
        uncurvedstatorhalf2dfemmprob ( Inputs.NSlots, ...
                                       ypole / slotsperpole, ...
                                       ycoil, ...
                                       yshoegap, ...
                                       xyoke, ...
                                       xcoil, ...
                                       xshoebase, ...
                                       xshoegap, ...
                                       xoffset, ...
                                       side, ...
                                      'NWindingLayers', Inputs.NWindingLayers, ...
                                      'FemmProblem', FemmProblem, ...
                                      'ShoeGapMaterial', Inputs.ShoeGapMaterial, ...
                                      'ShoeGapRegionMeshSize', Inputs.ShoeGapRegionMeshSize, ...
                                      'Tol', Inputs.Tol, ... 
                                      'DrawCoilInsulation', Inputs.DrawCoilInsulation, ...
                                      'CoilInsulationThickness', Inputs.CoilInsulationThickness, ...
                                      'CoilBaseFraction', Inputs.CoilBaseFraction );
    
end

