function [dx, bouyancy_force, excitation_force_heave, ...
    excitation_force_surge, radiation_force_heave, ...
    radiation_force_surge, FBDh, FBDs, wave_height] = buoyodesim(t, x, simoptions, Fexternal)
% buoyodesim: solves the rhs of the system of differential equations
% decribing the forces acting on a heaving buoy, and also determines the
% excitation, radiation, and buoyancy forces acting on the buoy.
%
%     
    
    dx = zeros (size (x));
    
    xBh = x(1,:);
    vBh = x(2,:);
    vBs = x(4,:);
    
    % Get the solution indices for the hydrodynamic variables
    buoyradinds = (5:4+(2*simoptions.NRadiationCoefs));
    
    % calculate the forces acting on the buoy
    [ buoyforcedx, ...
      bouyancy_force, ...
      excitation_force_heave, ...
      excitation_force_surge, ...
      radiation_force_heave, ...
      radiation_force_surge, ...
      FBDh, ...
      FBDs, ...
      wave_height]  = buoyodeforces (t, x(buoyradinds), xBh, vBh, vBs, simoptions);

    % copy the force derivatives to the derivatives vector at the
    % appropriae point
    dx(buoyradinds,:) = buoyforcedx;
    
    % Buoy acceleration in heave
    heavevelind = 2;

    dx(heavevelind,1) = real ( (excitation_force_heave + ...
                      radiation_force_heave + ...
                      bouyancy_force + ...
                      FBDh + ...
                      Fexternal(1)) / (simoptions.BuoyParameters.mass_external + ...
                                       simoptions.BuoyParameters.HM_infinity) ...
                             );

	dx(heavevelind,1) = dx(heavevelind,1) * simoptions.SeaParameters.ConstrainHeave;
    
    % Buoy acceleration in surge
    surgevelind = 4;

    dx(surgevelind,1) = real ( (excitation_force_surge + ...
                    radiation_force_surge + ...
                    FBDs + ...
                    Fexternal(2)) / (simoptions.BuoyParameters.mass_external + ...
                                     simoptions.BuoyParameters.SM_infinity) ...
                             );
                                 
	dx(surgevelind,1) = dx(surgevelind,1) * simoptions.SeaParameters.ConstrainSurge;
    
    % The differentials of the positions are the velocities
    dx(1,:) = vBh;
    dx(3,:) = vBs;
       
end