function l11 = cplateL11(r_o, a)

    roVa = r_o./a;
    
    l11 = (1/64) .* ( ...
             1 ...
             + 4.*(roVa).^2 ...
             - 5.*(roVa).^4 ...
             - 4.*(roVa).^2 .* (2 + (roVa).^2) .* log(a./r_o) ... 
                     );

end