function l17 = cplateL17(r_o, a, v)

    roVa = r_o ./ a;
    
    l17 = 0.25 .* ( ...
        1 ...
        - ((1 - v)./ 4) .* (1 - roVa.^4) ...
        - roVa.^2 .* ( 1 + (1+v).*log(a./r_o) ) ...
                   );

end