function y = GenericYDefAnnularPlateUniformDistPressure(yb, D, thetab, F1, Mrb, F2, Qb, F3, q, G11, r)

    y = yb ...
        + thetab.*r.*F1 ...
        + Mrb.*(r.^2./D).*F2 ...
        + Qb.*(r.^3./D).*F3 ...
        - q.*(r.^4./D).*G11;

end