function FemmProblem = femmprob_ACPMSM(design, pos, varargin)
% Generates an mfemm FemmProblem structure describing a linear air-cored
% permanent magnet machine
%
% ACPMSM machine diagram with dimensions shown below:
%
%          dbi  lm        dg               g    lm   dbi
%         <---><---><------------>:      <------><--><---->
%         |    |___        |______:______|        ___|    |  ^
%         |    |   |     ^ |             |    ^  |   |    |  :
%         |    |   |  Wc : |             |    :  |   |    |  :
%         |    |   |     v |_____________|    :  |   |    |  :
%         |    |   |       |             |    :  |   |    |  :
%         |    |   |       |_____________|    :  |   |    |  :
%         |    |   |       |             |    :  |   |    |  :
%         |    |   |       |             | bp :  |   |    |  : Taup
%         |    |   |       |_____________|    :  |   |    |  :
%         |    |   |   Ws^ |             |    :  |   |    |  :
%         |    |   |     v |_____________|    :  |   |    |  :
%         |    |   |       |             |    :  |   |    |  :
%         |    |   |       |             |    :  |   |    |  :
%         |    |___|       |_____________|    v  |___|    |  :
%         |    |           |             |           |    |  v   
%                          <------------->
%                                 Hc
%                   <---------------------------->
%                                 gap
%

% Created by Richard Crozier 2013

    Inputs.NWindingLayers = 1;
    Inputs.CoilCurrent = [];
    Inputs.CurrentDensity = [];
    
    Inputs = parse_pv_pairs(Inputs, varargin);
    
    if isempty(Inputs.CoilCurrent) && isempty(Inputs.CurrentDensity)
        Inputs.CoilCurrent = 0;
    end
    
    % Add some labels
    simwidth = sqrt((2*(design.lm+design.dg+design.dbi))^2 + (2*design.Taup)^2);
    mshsz = min(simwidth / 75, sqrt(simwidth^2 + (2*design.Taup)^2) / 150); % changed mesh density

    [FemmProblem, boundnames, magnames, ...
        wirename, maginds, wireind, steelind] = femmprob_FM(design);
    
    % draw wrapped mag region
    wrapperthickness = [ 0, design.dbi; 
                         0, 2*(design.dbi+design.lm);
                         0, 3*(design.dbi+design.lm); ];
                         
                         
    [FemmProblem, wrapperthickness, leftcentres, rightcentres, rightwmagouternodeids] = ...
        wrappedrectmagaperiodic(FemmProblem, ...
                                design.Taup, ...
                                design.bp, ...
                                design.lm, ...
                                design.lm/2 + design.dg, ...
                                pos, ...
                                wrapperthickness, ...
                                'MagnetMaterial', maginds, ...
                                'MagnetGroup', 3, ...
                                'MeshSize', mshsz);
                            
	FemmProblem = addblocklabel_mfemm(FemmProblem, ...
                                      rightcentres(1,1), ...
                                      rightcentres(1,2), ...
                                      'BlockType', '1117 Steel', ...
                                      'InGroup', 3, ...
                                      'MaxArea', mshsz);
    
    FemmProblem = addblocklabel_mfemm(FemmProblem, ...
                                      rightcentres(2,1), ...
                                      rightcentres(2,2), ...
                                      'BlockType', 'Air', ...
                                      'MaxArea', 15 * mshsz);
                                  
    FemmProblem = addblocklabel_mfemm(FemmProblem, ...
                                      rightcentres(3,1), ...
                                      rightcentres(3,2), ...
                                      'BlockType', 'Air', ...
                                      'MaxArea', 100 * mshsz);
    

	% draw wrapped mag region
    wrapperthickness = fliplr(wrapperthickness);
                         
                         
    [FemmProblem, wrapperthickness, leftcentres, rightcentres, leftwmagouternodeids] = ...
        wrappedrectmagaperiodic(FemmProblem, ...
                                design.Taup, ...
                                design.bp, ...
                                design.lm, ...
                                -(design.lm/2 + design.dg), ...
                                pos, ...
                                wrapperthickness, ...
                                'MagnetMaterial', maginds, ...
                                'MagnetGroup', 1, ...
                                'MeshSize', mshsz);
                            
	FemmProblem = addblocklabel_mfemm(FemmProblem, ...
                                      leftcentres(1,1), ...
                                      leftcentres(1,2), ...
                                      'BlockType', '1117 Steel', ...
                                      'InGroup', 1, ...
                                      'MaxArea', mshsz);
    
    FemmProblem = addblocklabel_mfemm(FemmProblem, ...
                                      leftcentres(2,1), ...
                                      leftcentres(2,2), ...
                                      'BlockType', 'Air', ...
                                      'MaxArea', 15 * mshsz);
                                  
    FemmProblem = addblocklabel_mfemm(FemmProblem, ...
                                      leftcentres(3,1), ...
                                      leftcentres(3,2), ...
                                      'BlockType', 'Air', ...
                                      'MaxArea', 100 * mshsz);
                                  
	% link the sets of magnets
    [FemmProblem, ~, boundname] = addboundaryprop_mfemm(FemmProblem, 'Periodic',  4);
    
    FemmProblem = addsegments_mfemm(FemmProblem, ...
                                    leftwmagouternodeids(2), ...
                                    rightwmagouternodeids(1), ...
                                    'BoundaryMarker', boundname);
                                  
	FemmProblem = addsegments_mfemm(FemmProblem, ...
                                    leftwmagouternodeids(3), ...
                                    rightwmagouternodeids(4), ...
                                    'BoundaryMarker', boundname);
                                
    % Now draw a single set of coils
    
    % Coil region properties
    if ~isempty(Inputs.CoilCurrent) && isempty(Inputs.CurrentDensity)
        % Add coil circuit
        FemmProblem = addcircuit_mfemm(FemmProblem, 'Coil A', 'TotalAmps_re', Inputs.CoilCurrent);
        
        coilblockprops = struct('BlockType', wirename, ...
                                'MaxArea', mshsz, ...
                                'InCircuit', {'Coil A', 'Coil A'}, ...
                                'Turns',{design.CoilTurns, -design.CoilTurns} , ...
                                'InGroup', 10);    

    elseif isempty(Inputs.CoilCurrent) && ~isempty(Inputs.CurrentDensity)
        % FEMM expects J in MA/m^2 so divide by 1e6
        J = Inputs.CurrentDensity / 1e6;
        
        % Add a solid copper materials with the specified current density
        cuMaterials = newmaterial_mfemm('copper J A', ... 
                                        'Mu_x',1 , ...
                                        'Mu_y', 1, ...
                                        'H_c', 0, ...
                                        'J_re', J, ...
                                        'Sigma', 58, ...
                                        'Density', 8600);
                                 
        cuMaterials(2) = newmaterial_mfemm('-copper J A', ... 
                                           'Mu_x',1 , ...
                                           'Mu_y', 1, ...
                                           'H_c', 0, ...
                                           'J_re', -J, ...
                                           'Sigma', 58, ...
                                           'Density', 8600);
        
        FemmProblem = addmaterials_mfemm(FemmProblem, cuMaterials);
        
        coilblockprops = struct('BlockType', {'copper J A', '-copper J A'}, ...
                                'MaxArea', mshsz, ...
                                'InGroup', 10);
    end
    
    if Inputs.NWindingLayers == 2
        
        % double-layered
        
        FemmProblem = addrectregion_mfemm(FemmProblem, ...
                                          -design.Hc/2, ...
                                          (1.5*design.Taup)-(design.Wc/2), ...
                                          design.Hc/2, ...
                                          design.Wc, ...
                                          coilblockprops(1));
                                      
        FemmProblem = addrectregion_mfemm(FemmProblem, ...
                                          0, ...
                                          (0.5*design.Taup)-(design.Wc/2), ...
                                          design.Hc/2, ...
                                          design.Wc, ...
                                          coilblockprops(2));
%         
%         mi_drawrectangle(-hc/2, (1.5*Taup)-(Wc/2), 0, (1.5*Taup)+(Wc/2));
%         
%         mi_drawrectangle(0, (0.5*Taup)-(Wc/2), hc/2, (0.5*Taup)+(Wc/2));
%         
%         coilxyCoords = rectcentre([-hc/2; 0], ...
%                                   [1.5*Taup-(Wc/2); 0.5*Taup-(Wc/2)], ...
%                                   [0; hc/2], ...
%                                   [1.5*Taup+(Wc/2); 0.5*Taup+(Wc/2)]);
                              
    elseif Inputs.NWindingLayers == 1
        
        % single-layered
        FemmProblem = addrectregion_mfemm(FemmProblem, ...
                                          -design.Hc/2, ...
                                          (1.5*design.Taup)-(design.Wc/2), ...
                                          design.Hc, ...
                                          design.Wc, ...
                                          coilblockprops(1));
                                      
        FemmProblem = addrectregion_mfemm(FemmProblem, ...
                                          -design.Hc/2, ...
                                          (0.5*design.Taup)-(design.Wc/2), ...
                                          design.Hc, ...
                                          design.Wc, ...
                                          coilblockprops(2));
                                      
%         mi_drawrectangle(-hc/2, (1.5*Taup)-(Wc/2), hc/2, (1.5*Taup)+(Wc/2));
%         mi_drawrectangle(-hc/2, (0.5*Taup)-(Wc/2), hc/2, (0.5*Taup)+(Wc/2));
%         coilxyCoords = rectcentre([-hc/2; -hc/2], ...
%                                   [1.5*Taup-(Wc/2); 0.5*Taup-(Wc/2)], ...
%                                   [hc/2; hc/2], ...
%                                   [1.5*Taup+(Wc/2); 0.5*Taup+(Wc/2)]);
    end
    
    FemmProblem = addblocklabel_mfemm(FemmProblem, ...
                                      0, ...
                                      design.Taup, ...
                                      'BlockType', 'Air', ...
                                      'MaxArea', mshsz);
                                  
end