function reportstrs = designreport_RADIAL(design, simoptions, reportstrs, varargin)
% produces a radial flux electrical machine design report in LaTeX format,
% and optionally prduces the pdf using pdflatex
%
% designreport_RADIAL can also be used to extend a report produced by a
% higher level function by passing in the existing report strings.
%
% Syntax
%
% designreport_RADIAL(design, simoptions)
% designreport_RADIAL(design, simoptions, reportstrs)
% reportstrs = designreport_RADIAL(...)
% 
% Input
%
%
% Output
%
%   reportstrs - cell array of strings containing the report
%

    if nargin < 3
        reportstrs = {};
    end
    
    options.ReportDir = '';
    if nargout == 0
        options.MakePdf = true;
        options.WriteOutReport = true;
    else
        options.MakePdf = false;
        options.WriteOutReport = false;
    end
    options.ReportTemplatePath = fullfile(getmfilepath('designreport_AM'), 'design_report_template.tex');
    
    options = parseoptions(options, varargin);
    
    % generate table of design dimensions
    
    % radial flux rotor dimensions
    tabledata = { ...
        '$R_{mi}$', 'Inner Magnet radius. (m)', design.Rmi;
        '$R_{mo}$', 'Outer Magnet radius. (m)', design.Rmo;
        '$R_{mm}$', 'Mean magnet radius. (m)', design.Rmm;
        '$R_{bi}$', 'Inner field back iron radius. (m)', design.Rbi;
        '$R_{bo}$', 'Outer field back iron radius. (m)', design.Rbo;
        'g', 'Air gap (mm)', design.g * 1000;
        '$t_m$',    'Magnet thickness in radial direction. (m)', design.tm;
        '$t_{bi}$', 'Back Iron thinckness in radial direction. (m)', design.tbi;
        '$\theta_{p}$', 'Pole pitch angle. (rad)', design.thetap;
        '$\theta_{m}$', 'Magnet pitch angle. (rad)', design.thetam;
        '$\theta_{p}$', 'Pole pitch angle. (degrees)', rad2deg(design.thetap);
        '$\theta_{m}$', 'Magnet pitch angle. (degrees)', rad2deg(design.thetam);
        '$\tau_{pm}$', 'Pole pitch at mean magnet radius. (m)', design.thetap*design.Rmm;
        '$\tau_{mm}$', 'Magnet pitch at mean magnet radius. (m)', design.thetam*design.Rmm;
        '$l_s$',    'Stack length. (m)', design.ls;
        '', 'Magnet Skew (Fraction of Pole)', design.MagnetSkew(1);
    };

    % generate the LaTex table of the outputs
    colheadings = {};
    rowheadings = {};
    colsep = ' & '; 
    rowending = ' \\';
    fms = '.3f';

    % displaytable(cell2mat(data(:,2)), colheadings,wid,fms,rowheadings, fid, colsep, rowending)
    
    fname = tempname;
    
    fid = fopen(fname, 'w');
    
    if fid == -1
        error('Temporary file could not be opened.');
    end
    
    displaytable(tabledata, colheadings, [30, 60, 20], fms, rowheadings, fid, colsep, rowending);
    
    % close the file
    fclose(fid);
    
    radrotordimstablestrs = txtfile2cell(fname);
    
radialreportstrs = [{...
'% Beginning section of report generated by designreport_RADIAL.m';
'\begin{table}[htb]';
'\centerline{';
'\begin{tabular}{lll}'
'\toprule';
'Dimension & Description & Value \\';
'\midrule';
}; ...
radrotordimstablestrs;
{...
'\bottomrule';
'\end{tabular}';
'}';
'\caption{Field dimensions.}';
'\end{table}';
'% FloatBarrier requires the placeins package';
'\FloatBarrier{}';
'';
}; ...
];

    % append stuff common to all machines
    radialreportstrs = designreport_ROTARY(design, simoptions, radialreportstrs, options);
    
    % append the report strings
    reportstrs = [ reportstrs;
                   radialreportstrs ];

end