function results = prallocresfcn_linear_mvgfield_system(design, simoptions, T, Y)

    % test the size of the arrays needed for preallocation by calling the 
    [
        results.ydot(1,:),...
        results.EMF(1,:),...
        results.Fpto(1,:),...
        results.xT(1,:),...
        results.vT(1,:),...
        results.Ffea_heave(1,:),...
        results.Ffea_surge(1,:),...
        results.FBDh(1,:),...
        results.FBDs(1,:),...
        results.buoyancy_force(1,:),...
        results.excitation_force_heave(1,:),...
        results.excitation_force_surge(1,:),...
        results.radiation_force_heave(1,:),...
        results.radiation_force_surge(1,:),...
        results.dpsidxR(1,:), ...
        results.Ffield(1,:), ...
        results.Faddbuoy(1,:) ...
     ] = feval(simoptions.ODESim.EvalFcn, T(1,:), Y(1,:)', design, simoptions);
     
    % Now preallocate arrays of the correct sizes
    fn = fieldnames(results);
    
    for i = 1:numel(fn)
        
        results.(fn{i}) = zeros(numel(T), size(results.(fn{i}),2));
        
    end

end
