function quitallslaves(filepath)
% deletes all mat files starting with slaveID_ in a directory
%
% Syntax
%
% mcore.quitallslaves()
% mcore.quitallslaves(filepath)
%
% Description
%
% Deletes all files with the pattern 'slaveID_*.mat' in a given directory.
% Slave processes started using mcore.startslave create files with this
% pattern and monitor their prescence. If their associated file is not
% present they terminate. If mcore.quitallslaves is called without a file
% path it uses the default filepath as returned by
% mcore.defaultmulticoredir().
%
% Input
%
% filepath - is the directory in which the slave Id files generated by
%   mcore.startslave will be found for deletion.
%

    if nargin < 1
        
        filepath = mcore.defaultmulticoredir ();

        fprintf ('No mutlicore comms directory path supplied, will look for slave files in default directory:\n%s\n', filepath);

    end

    if exist (filepath, "dir") == 7
        
        slave_id_files = dir (fullfile (filepath, 'slaveID_*.mat'));
        
        if numel(slave_id_files) > 0
        
            fprintf ('Deleting %d slave ID files in directory %s\n', numel(slave_id_files), filepath);

            delete(fullfile(filepath, 'slaveID_*.mat'));

        else

            fprintf ('No slave id files to delete were found in %s\n', filepath);

        end
    else

        error ('Directory %s does not exist\n', filepath);

    end
    
end