function [flux_linkage, FEF, lossinfo] = feaode_RADIAL_SLOTTED (design, simoptions, theta, Icoils)

    [ FEF, ...
      lossinfo.BxCoreLossData, ...
      lossinfo.ByCoreLossData, ...
      ~, ...
      flux_linkage ] = feasim_RADIAL_SLOTTED (design, simoptions, theta, ...
                                              'IsInitialisation', false);

end