% Test_fluxlinkagefrm2dAgrid.m

Test_simfun_TORUS_CORELESS

%%
design.psilookup = linspace(0, 1, 10);

tic;
% extract the flux linkage for the coils from the position of minimum
% flux linkage to maximum flux linkage. The scale factor is one as the
% coil height, and therefore area are already scaled to the pole pitch
polyfl = ...
    fluxlinkagefrm2dApoly(-(design.outermagsep/2) + design.g, ...
                          -design.tauco/(2*design.taupm), ...
                          -(design.outermagsep/2) + design.g, ...
                           design.tauci/(2*design.taupm), ...
                           design.tc, ...
                           (design.tauco - design.tauci)/(2*design.taupm), ...
                           [zeros(numel(design.psilookup(1,:)), 1), (design.psilookup(1,:)+1.5)'], ...
                           design.APoly, ...
                           design.CoilTurns, ...
                           design.Rmo - design.Rmi, ...
                           1);
toc;
tic;
% extract the flux linkage for the coils from the position of minimum
% flux linkage to maximum flux linkage. The scale factor is one as the
% coil height, and therefore area are already scaled to the pole pitch
gridfl = ...
    fluxlinkagefrm2dAgrid(-(design.outermagsep/2) + design.g, ...
                          -design.tauco/(2*design.taupm), ...
                          -(design.outermagsep/2) + design.g, ...
                           design.tauci/(2*design.taupm), ...
                           design.tc, ...
                           (design.tauco - design.tauci)/(2*design.taupm), ...
                           [zeros(numel(design.psilookup(1,:)), 1), (design.psilookup(1,:)+1.5)'], ...
                           design.X, design.Y, design.A, ...
                           design.CoilTurns, ...
                           design.Rmo - design.Rmi, ...
                           1/design.taupm);    
toc;
tic;
% extract the flux linkage for the coils from the position of minimum
% flux linkage to maximum flux linkage. The scale factor is one as the
% coil height, and therefore area are already scaled to the pole pitch
tempgridfl = ...
    tempfluxlinkagefrm2dAgrid(-(design.outermagsep/2) + design.g, ...
                          -design.tauco/(2*design.taupm), ...
                          -(design.outermagsep/2) + design.g, ...
                           design.tauci/(2*design.taupm), ...
                           design.tc, ...
                           (design.tauco - design.tauci)/(2*design.taupm), ...
                           [zeros(numel(design.psilookup(1,:)), 1), (design.psilookup(1,:)+1.5)'], ...
                           design.X, design.Y, design.A, ...
                           design.CoilTurns, ...
                           design.Rmo - design.Rmi, ...
                           1/design.taupm);    
toc;                       
                       
displaytable([polyfl, gridfl, tempgridfl], {'polyfl', 'gridfl', 'tempgridfl'}, 15);


