function [results, design] = splitsystemresfun_AM(T, Y, design, simoptions, results)
% completes the processing of data generated by
% splitodeelectricalresults_AM.m during an ODE simulation of an electrical
% machine using odesplit
%
% Syntax
%
% [results, design] = splitsystemresfun_AM(T, Y, design, simoptions, results)
%
%

% Copyright Richard Crozer, The University of Edinburgh

    % determine the actual simulation time
    design.SimTimeSpan = results.maxT - simoptions.tspan(1);

    % Get the peak coil current and current densities
    [design.ICoilPeak, maxIind] = max(results.ICoilPeak);
    
    design.JCoilPeak = design.ICoilPeak / design.ConductorArea;
    
    % Calculate the rms coil current from the supplied current integral
    design.ICoilRms = sqrt(results.coilIsquaredsum ./ ( design.SimTimeSpan ));

    % The rms coil current density
    design.JCoilRms = design.ICoilRms(maxIind) / design.ConductorArea;

    % The max current density in the conductor
%     results.JCoilPeak = results.ICoilPeak(maxIind) /
%     design.ConductorArea;

    % Calculate the rms phase EMF from the supplied EMF integral
    design.EMFPhaseRms = sqrt(results.phaseEMFsquaredsum(maxIind) ./ ( design.SimTimeSpan ));

    % Get the peak phase current 
    design.IPhasePeak = design.ICoilPeak .* design.Branches;
    
    % Get the rms phase current
    design.IPhaseRms = sqrt(results.phaseIsquaredsum(maxIind)  ./ ( design.SimTimeSpan ));
    
    % Store the peak phase EMF in the design structure
    design.EMFPhasePeak = max(results.EMFPhasePeak);

    % Store the total extracted energy summed for all generators in the
    % design structure
    design.EnergyLoadTotal = sum(results.EnergyLoadTotal) * simoptions.NoOfMachines;
    
    design.EnergyPhaseRTotal = results.EnergyPhaseRTotal * simoptions.NoOfMachines;

    % Calculate the mean power output from the supplied power integral
    % of the simulation
    design.PowerLoadMean = design.EnergyLoadTotal / (design.SimTimeSpan);

    % put the peak recorded power in the design structure
    design.PowerLoadPeak = results.PowerLoadPeak * simoptions.NoOfMachines;

    % store the mean power losses in the phase resistances
    design.PowerPhaseRMean = design.EnergyPhaseRTotal / (design.SimTimeSpan);

    design.PowerSystemMean = design.PowerPhaseRMean + design.PowerLoadMean;

end