function reportstrs = designreport_ROTARY(design, simoptions, reportstrs, varargin)
% produces strings containing a rotary machine design report
%
% Syntax
%
% reportstrs = designreport_ROTARY(design, simoptions, reportstrs)
%
% 

    if nargin < 3
        reportstrs = {};
    end
    
    % generate table of design dimensions
    
    if isfield(design, 'TorquePtoPeak')
        TorquePtoPeak = design.TorquePtoPeak;
    else
        TorquePtoPeak = 'N/A';
    end
    
    if isfield(design, 'slm_coggingforce')
        maxcoggingf = slmpar(design.slm_coggingforce, 'maxfun');
    else
        maxcoggingf = 'N/A';
    end
    
    if isfield(design, 'gforce')
        gforce = abs(design.gforce(1));
    else
        gforce = 'N/A';
    end
    
    if isfield(design, 'FrequencyPeak')
        FrequencyPeak = design.FrequencyPeak;
    else
        FrequencyPeak = 'N/A';
    end
    
    if isfield(design, 'TorqueRippleFactor')
        TorqueRippleFactor = design.TorqueRippleFactor * 100;
    else
        TorqueRippleFactor = 'N/A';
    end
    
    % rotary machine properties
    tabledata = { ...
        'Max PTO Torque (Nm)', TorquePtoPeak;
        'Max Magnet Cogging Force (N)', maxcoggingf;
        'Max Magnet Cogging Torque (Nm)', maxcoggingf * design.Rmm;
        'Max Estimated Electrical Frequency (Hz)', FrequencyPeak;
        'Torque Ripple Factor (\%)', TorqueRippleFactor;
        'Air Gap Closing Force Per Pole (N)', gforce;
    };

    % generate the LaTex table of the outputs
    colheadings = {};
    rowheadings = {};
    colsep = ' & '; 
    rowending = ' \\';
    fms = '.3f';

    % displaytable(cell2mat(data(:,2)), colheadings,wid,fms,rowheadings, fid, colsep, rowending)
    
    fname = tempname;
    
    fid = fopen(fname, 'w');
    
    if fid == -1
        error('Temporary file could not be opened.');
    end
    
    displaytable(tabledata, colheadings, [60, 20], fms, rowheadings, fid, colsep, rowending);
    
    % close the file
    fclose(fid);
    
    rotarydimstablestrs = txtfile2cell(fname);
    
rotaryreportstrs = [{...
'% Beginning section of report generated by designreport_RORARY.m';
'\begin{table}[htb]';
'\centerline{';
'\begin{tabular}{ll}'
'\toprule';
'Description & Value \\';
'\midrule';
}; ...
rotarydimstablestrs;
{...
'\bottomrule';
'\end{tabular}';
'}';
'\caption{Rotary specific simulation outputs.}';
'\end{table}';
'% FloatBarrier requires the placeins package';
'\FloatBarrier{}';
'';
}; ...
];

    % append stuff common to all machines
    radialreportstrs = designreport_AM(design, simoptions, rotaryreportstrs, options);
    
    % append the report strings
    reportstrs = [ reportstrs;
                   radialreportstrs ];

end